### ISSUE TITLE
geometry parsing of basic shapes

### ISSUE THREAD

**Issue by mm-wang** [mm-wang/metashape#1]
- [ ] develop features
- [ ] pick a categorization: energy or other category
- [x] volume
- [x] area
- [x] bounding box
- [ ] voids
- [ ] rays
- [x] slicing
- [x] area of curves

**Comment by tkmmark** [comment]
List of features to do: 
(please add)

from Mark
- [x] Distance of volume centroid to floor plate centroid (picks up cantilever and eccentricity)
- [x] Volume moments
- [ ] Sub-massing (non-trivial).
- [ ] Closest primitive shape
- [x] BREP topology information: edge, face, vertex count
- [x] Volume / Bounding Box Volume Ratio _(volumetric spread indicator)_
- [ ] Angular difference betweenprinciple component of massing volume and that for ground floor _(indicator for twist)_

from Nate

- [x] area
- [x] volume
- [x] bounding box hwd
- [x] centroid xyz
- [ ]

**Comment by Nate-Holland** [comment]
Nate's feature list
area
volume
bounding box hwd
centroid xyz

**Comment by Nate-Holland** [comment]
- [ ] test

**Comment by Nate-Holland** [comment]
Nate's feature list
- [ ] area
- [ ] volume
- [ ] bounding box hwd
- [ ] centroid xyz

**Comment by saeranv** [comment]
Alright guys I'm going to be trying to figure out the view factor calculations. Honeybee has two different ways of doing this I think we can do.

**Comment by tkmmark** [comment]
@Nate-Holland  I combined our lists together.
For bounding box, it might be nice to find the planes for constructing the best fitting bounding box (eg: no gap sapces in the bounding box of an extruded diamond)

**Comment by Huangkuncheng** [comment]
Hello, I'm a graduate student. I'm working on a similar project. Your code is very enlightening to me, but I don't know how to use these codes and files. I'd appreciate it if you could explain

**Comment by mm-wang** [comment]
This was developed for a hackathon and has not been maintained.
